"""
conftest.py  Shared Configuration for all pytest tests

This file is automatically loaded by pytest before running any tests.
It defines:
  - Data routes (configurable without touching the algorithm code).
  - Reusable fixtures among tests.
  - An auxiliary function for creating in-memory test workbooks. 
"""

import os
import sys
import shutil
import pytest
import openpyxl

# ==== CONFIGURABLE ROUTES ====
# If you move the files, you will only need to change these constants.

# Project root directory (where ebdtFunctions.py and real .xlsm files reside)
CODE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# Small test data (subset of real data)
FIXTURES_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "fixtures"))

# Reference results (generated by running the full pipeline)
GOLDEN_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "golden"))

# ==== ENSURE THAT THE CODE IS IMPORTABLE ====
sys.path.insert(0, CODE_DIR)


# ==== ROUTE FIXTURES ====

@pytest.fixture
def fixtures_dir():
    #Path to the folder with the small test data
    return FIXTURES_DIR


@pytest.fixture
def golden_dir():
    #Path to the folder with the reference results
    return GOLDEN_DIR


@pytest.fixture
def code_dir():
    #Path to the folder with the project root
    return CODE_DIR


@pytest.fixture
def tmp_run_dir(tmp_path):
    """
    Create an isolate temporary directory with everything needed to
    run the complete pipeline (mini fixtures).

    Created structure:
        tmp_path/
        - MCF7.xlsm              copy the mini fixture
        - requiredData/
            - kinaseInhibitionSpecificity.csv
            - listOfKinases.csv
    """
    # Copy the excel mini file with the name the code expects
    shutil.copy(
        os.path.join(FIXTURES_DIR, "MCF7_mini.xlsm"),
        os.path.join(tmp_path, "MCF7.xlsm")
    )
    # Copy required CSV
    req_src = os.path.join(FIXTURES_DIR, "requiredData")
    req_dst = os.path.join(tmp_path, "requiredData")
    shutil.copytree(req_src, req_dst)

    return str(tmp_path)


@pytest.fixture
def tmp_run_dir_real(tmp_path):
    """
    Same as tmp_run_dir but with real data (MCF7 and HL60 complete).
    Used only in regression tests (marked as @pytest.mark.slow).
    """
    for cell_line in ["MCF7", "HL60", "NTERA2"]:
        shutil.copy(
            os.path.join(CODE_DIR, f"{cell_line}.xlsm"),
            os.path.join(tmp_path, f"{cell_line}.xlsm")
        )
    req_src = os.path.join(CODE_DIR, "requiredData")
    req_dst = os.path.join(tmp_path, "requiredData")
    shutil.copytree(req_src, req_dst)

    return str(tmp_path)


# ==== AUXILIARY FUNCTION TO CREATE IN-MEMORY WORKBOOKS ====

def make_workbook(fold_rows, pvalue_rows):
    """
    Creates a workbook in openpyxl in memory with sheets 'fold' and 'pvalue'.

    Parametres:
    fold_rows : list of list
    pvalue_rows : list of list
    Returns
    openpyxl.Workbook 
    """
    wb = openpyxl.Workbook()
    wb.remove(wb.active)  # remove the blank sheet that is created by default

    for sheet_name, rows in [("fold", fold_rows), ("pvalue", pvalue_rows)]:
        ws = wb.create_sheet(sheet_name)
        for row in rows:
            ws.append(row)

    return wb
